### ISSUE TITLE
pip repository is outdated

### ISSUE THREAD

**Issue by dickshaydle** [cqparts/cqparts#63]
Hi,
i came to cqparts because of the great way to create threads. But this doesnt work correctly if I install cqparts via pip because the code there is older. The current version from github works fine.

Is there a other nice way to install cqparts and keep it up to date?
Can the "~/.FreeCAD/Mod" folder be used for this maybe?

**Comment by jmwright** [comment]
@dickshaydle I can't answer for @fragmuffin about pip, but I'm the maintainer of the CadQuery module/workbench for FreeCAD. I wouldn't be opposed to including cqparts in that workbench so that it would always be accessible and could be updated through the FreeCAD addons manager.

**Comment by fragmuffin** [comment]
@dickshaydle 

> i came to cqparts because of the great way to create threads

I'm quite proud of how threads works... or rather, I will be when #1 is fixed...
Due to #1 causing exceptions, or invalid solids, I've made all threads "simple" by default, meaning that unless you explicitly set the parameter `_simple=False`, all threads will render as a cylinder.
Of course, when #1 is fixed, that default behaviour will be removed.

> But this doesnt work correctly if I install cqparts via pip because the code there is older. The current version from github works fine

That's very interesting, because I haven't made any changes to threads since release (comparison: [release...master](https://github.com/fragmuffin/cqparts/compare/e16111c...d3b2893))
Could you be more specific about what's not working from the pip released version?, a code example would help.

> Can the "~/.FreeCAD/Mod" folder be used for this maybe?

To import `cqparts` directly from a git repo' you can use its parent directory `~/.FreeCAD`

```bash
# change this to your path
cqparts_path=~/git-repo-path/cqparts

# just cqparts
ln -s $cqparts_path/src/cqparts ~/.FreeCAD/cqparts

# to include all the cqparts_* libs as well
cqparts_libs=$(find $cqparts_path/src/ -mindepth 1 -maxdepth 1 -type d -printf %f\\n)
for lib_name in $cqparts_libs ; do
    ln -s $cqparts_path/src/$lib_name ~/.FreeCAD/$lib_name
done
```

**Comment by fragmuffin** [comment]
@jmwright I wouldn't be opposed to adding `cqparts` to the workbench either :smile:.

**Comment by fragmuffin** [comment]
@dickshaydle 

I just thought of another reason it might not work...
`cqparts` is the core library, whereas threads come from `cqparts_fasteners` which is a library that requires `cqparts`.

```bash
pip install cqparts cqparts_fasteners
```
